// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcokMdnyqjqoxORzmPUlPEz8Y_aJzKOE',
    appId: '1:1030661724646:web:a18e04040cdafc108a5e27',
    messagingSenderId: '1030661724646',
    projectId: 'streaming-4c11e',
    authDomain: 'streaming-4c11e.firebaseapp.com',
    storageBucket: 'streaming-4c11e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDv91vzrFHADOAp48LgDpVyqv5VGJN2vI',
    appId: '1:1030661724646:android:4a8b770bff0eae508a5e27',
    messagingSenderId: '1030661724646',
    projectId: 'streaming-4c11e',
    storageBucket: 'streaming-4c11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF48xXLvF8avcKtA92x3MKZfhsv74CIVw',
    appId: '1:1030661724646:ios:9f63f5786ad4e3ac8a5e27',
    messagingSenderId: '1030661724646',
    projectId: 'streaming-4c11e',
    storageBucket: 'streaming-4c11e.appspot.com',
    iosClientId: '1030661724646-6btfk2j1h9e030b12v2s0h6id58np0qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF48xXLvF8avcKtA92x3MKZfhsv74CIVw',
    appId: '1:1030661724646:ios:9f63f5786ad4e3ac8a5e27',
    messagingSenderId: '1030661724646',
    projectId: 'streaming-4c11e',
    storageBucket: 'streaming-4c11e.appspot.com',
    iosClientId: '1030661724646-6btfk2j1h9e030b12v2s0h6id58np0qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiFlutter',
  );
}
